### ISSUE TITLE
Negative Numbers are incorrectly highlighted

### ISSUE THREAD

**Issue by Adrian-Turjak** [atom/language-yaml#102]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Yaml syntax highlighing incorrectly highlights a negative number as a str rather than a number.

### Steps to Reproduce

1. open yaml file
2. make key value where value is negative int
3. observer incorrect syntax highlighting

Below used for testing:
```yaml
some_wrapper:
  positive_int: 1234
  negative_int: -1234
  positive_float: 123.4
  negative_float: -123.4
```

**Expected behavior:** 
Negative numbers should correctly be highlighted as numbers not str.

**Actual behavior:**
Negative numbers are highlighted as strings.

**Reproduces how often:**
100%

### Versions
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by Adrian-Turjak** [comment]
@50Wliu ty!

**Comment by 50Wliu** [comment]
No problem!  This is scheduled for release in Atom 1.26 beta.
