### ISSUE TITLE
Leading tabs are illegal in YAML, maybe identify them visually?

### ISSUE THREAD

**Issue by BruceFletcher** [atom/language-yaml#23]
According to the YAML spec, tabs are not valid indentation characters, only spaces:

http://www.yaml.org/spec/1.2/spec.html#id2777534

"To maintain portability, tab characters must not be used in indentation, since different systems treat tabs differently."

This is tricky, because I don't think language-yaml can enforce the use of soft tabs in yaml files, but at the very least it would be helpful if it could, for instance, colour indenting hard tabs to make them obvious.

**Comment by 50Wliu** [comment]
> I don't think language-yaml can enforce the use of soft tabs in yaml files

Yes it can! :)
Creating a PR for it now that will also tokenize tabs as invalid.
