### ISSUE TITLE
Indicate the current full path to the current line entry

### ISSUE THREAD

**Issue by vemv-kantox** [atom/language-yaml#31]
Feature request, would be so handy for huge yml files!

![screen shot 2015-08-24 at 17 49 30](https://cloud.githubusercontent.com/assets/12593885/9444816/08acd5b0-4a89-11e5-858b-83303dea0064.png)

How can I know the full path of the yml entry corresponding to the current line (xxx.errors.messages.taken)? By scrolling and taking a lot of care...

Would be awesome if the plugin just told me at every moment the full path of the current entry.

Obviously the displayed value would change as one uses the cursor to move the current line.

Sounds cool and not too complicated to implement?

Cheers - Victor

**Comment by 50Wliu** [comment]
This package only handles the tokenization of YAML files.  Your suggestion sounds like it could be made into a package though.
