### ISSUE TITLE
YML files freezes Atom

### ISSUE THREAD

**Issue by andrefreitas** [atom/language-yaml#39]
When I have more than 2 yml files open, Atom freezes. This happens even with Safe Mode. I already tried doing a clean install and remove ~/.atom.

I am using OS X El Capitan and Atom 1.3.1

![screen shot 2015-12-16 at 13 50 51](https://cloud.githubusercontent.com/assets/1192089/11842577/645e14d8-a3fc-11e5-9a61-fc8458a98e1e.png)

Note: the files are small.

**Comment by 50Wliu** [comment]
Please update to Atom 1.4.0-beta0: you seem to be experiencing an issue where the filenames are too similar and Atom can't properly compute a tab name for them.  That has been fixed in the latest beta.
