### ISSUE TITLE
Cannot assign *.neon file type

### ISSUE THREAD

**Issue by dibalaj** [atom/language-yaml#40]
Hello,

Nette PHP Framework uses YAML config style - but uses *.neon file extensions (look at https://ne-on.org/). How can I assign *.neon file type to YAML syntax?

**Comment by MaximSokolov** [comment]
Add to your config:
```coffee
"*":
  core:
    customFileTypes:
      "source.yaml": [
        "neon"
      ]
```
You can also add *.neon filetype to [yaml.cson#L3-L11](https://github.com/atom/language-yaml/blob/56cd8a40a18aa025526f6f0495a711c4280b7178/grammars/yaml.cson#L3-L11) and create a pull request

**Comment by dibalaj** [comment]
Thanks. I'll create a PR.
