### ISSUE TITLE
Mapping keys displayed with wrong color

### ISSUE THREAD

**Issue by sangimed** [atom/language-yaml#51]
As you can see in the screenshot below, the second key isn't rendered with the right color (red as the key "name").

- Atom version : 1.9.8
- Language-yaml plugin version : 0.26.0

![2016-08-17_175731](https://cloud.githubusercontent.com/assets/857405/17743572/689c259e-64a4-11e6-8856-c6831d07c136.png)

**Comment by 50Wliu** [comment]
I believe that this is a duplicate of #5.
