### ISSUE TITLE
Incorrect mulitline syntax highlighting

### ISSUE THREAD

**Issue by danilobuerger** [atom/language-yaml#64]
```
---
command:
  |
    echo '"test":'
    echo 'test'
```

Produces:

<img width="250" alt="screen shot 2017-01-11 at 12 53 41" src="https://cloud.githubusercontent.com/assets/996231/21847604/0013e364-d7fd-11e6-8b25-2efde0c02e76.png">

**Comment by 50Wliu** [comment]
Fixed by #62.
