### ISSUE TITLE
YAML highlighting of value portion of key-value for non-quoted, non-multiline strings continues onto next line erroneously

### ISSUE THREAD

**Issue by BlaineEXE** [atom/language-yaml#78]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

YAML highlighting for a key's value continues onto the next line when it is a simple, non-quoted string (not a list, another key, a multiline string (with | or >), etc, and the highlighting should *not* continue.

Simple test case in YAML file to reproduce

```yaml

this: key
is
highlighted
over
arbitrary
number
of
lines
```

**Expected behavior:** [What you expect to happen]
When using a simple, non-quoted string in YAML, I expect the next line's content to *not* be highlighted unless it is a quoted string, a list, a multiline string (with | or >), etc. In the example, 'is' begins a line that violates YAML's syntax. One suggestion that this case is the correct one is that trying to load a test yaml file in Python with the text will throw an error with the text `could not find expected ':'` on the example line "is".

**Actual behavior:** [What actually happens]
YAML highlighting for a key's value continues onto the next line when it is a simple, non-quoted string (not a list, another key, a multiline string (with | or >), etc. See image below.

![image](https://cloud.githubusercontent.com/assets/3989526/24226157/7c9e97bc-0f2a-11e7-966e-232874d5f8f5.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Versions
atom --version
Atom    : 1.14.4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.13
git 2.12.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
So yes, this is an issue.  However, it is a very difficult issue to fix.  I've made some (non-visible) progress with it in #74.

**Comment by BlaineEXE** [comment]
Thank you! I believe this issue is the root behind support for Jinja2 highlighting in YAML files: https://github.com/danielchatfield/atom-jinja2/issues/22

**Comment by jerowe** [comment]
I either have a similar or the same issue.

![yaml-syntax-highlighting](https://user-images.githubusercontent.com/5555526/34033885-982c148a-e195-11e7-8c8c-57ad741a8d91.png)

Syntax highlighting for a multiline string continues after the multiline string.

It happened very shortly after I updated all my atom packages, but I'm not sure what version I was on before.

**Comment by russianryebread** [comment]
I have a similar issue, though it's also erroneously highlighting a hidden char (space)

<img width="234" alt="screen shot 2018-02-01 at 12 55 00 pm" src="https://user-images.githubusercontent.com/747085/35694403-44fea356-074f-11e8-94a3-77e284a8dcc7.png">
