### ISSUE TITLE
Syntax highlighting after |- 

### ISSUE THREAD

**Issue by LydiaF** [atom/language-yaml#84]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Syntax highlighting is not working well after |- in YAML:
1. multi-line with colon is interpreted as a key
2. adding a colon at the end of the line with a markdown # at the beginning of the line is interpreted as a comment
3. cannot comment on the same line as 

### Steps to Reproduce

1. Ensure YAML formatting
2. Try this:
```
key: |-
  Lorem ipsum
key: |-
  Lorem ipsum:
test: |-
  # Lorem ipsum
test: |- 
  # Lorem ipsum:
test: |- #comment
  Lorem ipsum
```
**Expected behavior:**
![image](https://cloud.githubusercontent.com/assets/10000865/25557933/f5784be0-2d13-11e7-89d8-7eef47001e44.png)

**Actual behavior:**

![image](https://cloud.githubusercontent.com/assets/10000865/25557931/ee039004-2d13-11e7-92e3-e663ccb355d1.png)

**Reproduces how often:** 
all the time

### Versions

Atom : 1.16.0
Electron: 1.3.13
Chrome: 52.0.2743.83
Node: 6.5.0
apm: 1.16.1
npm: 3.10.5
node: 6.9.5 x64
python: 2.7.10
git: 2.6.1

**Comment by miloprice** [comment]
I ran into this with just `|`-denoted blocks as well.
