### ISSUE TITLE
entity.name.tag.yaml in block scalar 

### ISSUE THREAD

**Issue by mjbvz** [atom/language-yaml#94]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

For the yaml 

```yaml
Key1: |-
  a
  (?:
  a
  )
Key2: 1
```

**Expected behavior:** [What you expect to happen]
The contents of `key1` should be highlighted the same since they are part of the same block scalar

**Actual behavior:** [What actually happens]

<img width="135" alt="screen shot 2017-09-18 at 11 00 35 am" src="https://user-images.githubusercontent.com/12821956/30556719-ac4cfa80-9c60-11e7-8961-ca9834c34e5a.png">

The `(?:` is highlighted differently

**Additional Information**
The scope of the `(` in `(?:` is:

```
source.yaml
entity.name.tag.yaml
```

**Comment by 50Wliu** [comment]
Great news!  I just fixed this in #93.  It's currently scheduled to go out in Atom 1.22.0, though github.com may receive the changes earlier than that.
